version: "3.8"

services:
  ros2:
    build:
      context: docker/ros2
      args:
        - user_id=1000
        - ros_ws=/home/dockeruser/dev_ws

    volumes:
      - ./:/home/dockeruser/project
      - ./dev_ws:/home/dockeruser/dev_ws
      - ./docker/ros2/.ros:/home/dockeruser/.ros
      - ./docker/ros2/.gazebo/:/home/dockeruser/.gazebo

    ports:
      - "9090:9090"

    command: >
      bash -c "
      ros2 launch rosbridge_server rosbridge_websocket_launch.xml"
